name = "SearchLightMySQL"
uuid = "1297d576-4826-11ea-035e-9995c721bad1"
authors = ["Adrian Salceanu <e@essenciary.com>"]
version = "1.0.0"

[deps]
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MySQL = "39abe10b-433b-5dbd-92d4-e302a9df00cd"
SearchLight = "340e8cb6-72eb-11e8-37ce-c97ebeb32050"

[compat]
DBInterface = "2"
DataFrames = "1"
MySQL = "1"
SearchLight = "1, 0.22"
julia = "1"
